/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MedicineRouteImport } from './routes/medicine'
import { Route as FlockRouteImport } from './routes/flock'
import { Route as IndexRouteImport } from './routes/index'

const MedicineRoute = MedicineRouteImport.update({
  id: '/medicine',
  path: '/medicine',
  getParentRoute: () => rootRouteImport,
} as any)
const FlockRoute = FlockRouteImport.update({
  id: '/flock',
  path: '/flock',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flock': typeof FlockRoute
  '/medicine': typeof MedicineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flock': typeof FlockRoute
  '/medicine': typeof MedicineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flock': typeof FlockRoute
  '/medicine': typeof MedicineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flock' | '/medicine'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flock' | '/medicine'
  id: '__root__' | '/' | '/flock' | '/medicine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlockRoute: typeof FlockRoute
  MedicineRoute: typeof MedicineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/medicine': {
      id: '/medicine'
      path: '/medicine'
      fullPath: '/medicine'
      preLoaderRoute: typeof MedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flock': {
      id: '/flock'
      path: '/flock'
      fullPath: '/flock'
      preLoaderRoute: typeof FlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlockRoute: FlockRoute,
  MedicineRoute: MedicineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
